# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: xyz_development
  pool: 5
  username: postgres
  password: Mohabdu1

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: xyz_test
  pool: 5
  username: postgres
  password:	Mohabdu1

production:
  adapter: postgresql
  encoding: utf8
  database: xyz_production
  pool: 5
  username: 
  password:
